name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    lint:
        name: "Linting check with black"
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                python-version: ["3.11"]

        steps:
            - name: Checkout
            - uses:  actions/checkout@v5

            - name: Set up Python
            - uses: actions/setup-python@v5
            
            - name: Install Dependencies
            - run: |
                python -m pip install black

            - name: Run black check
            - run: |
                black --check .